### ISSUE TITLE
 Recurrence experiment

### ISSUE THREAD

**Issue by Jinn02-25** [cszhangzhen/HGP-SL#12]
Hello, I am very interested in your paper. I am reproducing your experiment, but I don’t know why it keeps prompting:TypeError: coalesce() got an unexpected keyword argument 'fill_value'

**Comment by Jinn02-25** [comment]
runfile('C:/Users/DELL/Desktop/git代码/HGP-SL-master/main.py', wdir='C:/Users/DELL/Desktop/git代码/HGP-SL-master')
Reloaded modules: sparse_softmax
Namespace(batch_size=512, dataset='PROTEINS', device='cuda:0', dropout_ratio=0.0, epochs=1000, lamb=1.0, lr=0.001, nhid=128, num_classes=2, num_features=4, patience=100, pooling_ratio=0.5, sample_neighbor=True, seed=777, sparse_attention=True, structure_learning=True, weight_decay=0.001)
Traceback (most recent call last):

  File "C:\Users\DELL\Desktop\git代码\HGP-SL-master\main.py", line 126, in <module>
    best_model = train()

  File "C:\Users\DELL\Desktop\git代码\HGP-SL-master\main.py", line 70, in train
    out = model(data)

  File "C:\Users\DELL\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\DELL\Desktop\git代码\HGP-SL-master\models.py", line 39, in forward
    x, edge_index, edge_attr, batch = self.pool1(x, edge_index, edge_attr, batch)

  File "C:\Users\DELL\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\Users\DELL\Desktop\git代码\HGP-SL-master\layers.py", line 203, in forward
    hop_data = self.neighbor_augment(hop_data)

  File "C:\Users\DELL\Desktop\git代码\HGP-SL-master\layers.py", line 31, in __call__
    data.edge_index, edge_attr = coalesce(edge_index, edge_attr, n, n, op='min', fill_value=fill)

TypeError: coalesce() got an unexpected keyword argument 'fill_value'

**Comment by cszhangzhen** [comment]
Hi,

This is because you use the latest torch-sparse. An older version of torch-sparse is needed, lower than 0.4.4.

**Comment by saiprasanna06** [comment]
Would it be possible to upload the yml file ? The dependencies are a tough nut to crack, since older versions are required. Thanks
