### ISSUE TITLE
AssertionError   assert trust_data or int(col.max()) < N 

### ISSUE THREAD

**Issue by lig97** [cszhangzhen/HGP-SL#19]
Hello, when I reproduce your code, when the model is trained normally until the 22nd epoch, the code has an error. Have you encountered this situation here? Do you have any ideas on how to solve it? Looking forward to your answer, thank you !!

Epoch: 0023 loss_train: 1.181976 acc_train: 0.696629 loss_val: 0.594611 acc_val: 0.720721 time: 119.426900s
Traceback (most recent call last):
  File "D:\pycharmprojects\pythongraph\HGP-SL-master\main.py", line 130, in <module>
    best_model = train()
  File "D:\pycharmprojects\pythongraph\HGP-SL-master\main.py", line 74, in train
    out = model(data)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\pycharmprojects\pythongraph\HGP-SL-master\models.py", line 39, in forward
    x, edge_index, edge_attr, batch = self.pool1(x, edge_index, edge_attr, batch)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\pycharmprojects\pythongraph\HGP-SL-master\layers.py", line 204, in forward
    hop_data = self.neighbor_augment(hop_data)
  File "D:\pycharmprojects\pythongraph\HGP-SL-master\layers.py", line 22, in __call__
    index, value = spspmm(edge_index, value, edge_index, value, n, n, n, True)
  File "D:\Anaconda3\lib\site-packages\torch_sparse\spspmm.py", line 30, in spspmm
    C = matmul(A, B)
  File "D:\Anaconda3\lib\site-packages\torch_sparse\matmul.py", line 140, in matmul
    return spspmm(src, other, reduce)
  File "D:\Anaconda3\lib\site-packages\torch_sparse\matmul.py", line 117, in spspmm
    return spspmm_sum(src, other)
  File "D:\Anaconda3\lib\site-packages\torch_sparse\matmul.py", line 107, in spspmm_sum
    sparse_sizes=(M, K), is_sorted=True)
  File "D:\Anaconda3\lib\site-packages\torch_sparse\tensor.py", line 38, in __init__
    trust_data=trust_data,
  File "D:\Anaconda3\lib\site-packages\torch_sparse\storage.py", line 79, in __init__
    assert trust_data or int(col.max()) < N
AssertionError

**Comment by cszhangzhen** [comment]
Hi, 

It works well on my server. It may be caused by the version of torch-sparse. My current version is 0.6.15.

**Comment by lig97** [comment]
Hi, I just took a look at my torch-sparse version, it is the same as your version, but the problem is still not solved, and an error will still appear. 

I am new to the graph convolutional neural network. Can you tell me why the code did not report an error at the beginning, but an error occurred at the 24th epoch? I ran the code many times and found that the epoch of the error is not fixed and will change. Looking forward to your answer, thank you !!

**Comment by cszhangzhen** [comment]
Hi, I can not reproduce your error on my server. Could you provide more information? Which dataset are you using? What are the hyper-parameters?

My current environments:
pytorch 1.13.1
torch_geometric 2.2.0
torch_sparse 0.6.15
torch_scatter 2.1.0
torch_cluster 1.6.0

**Comment by lig97** [comment]
Hello, thank you for your previous answers. Those problems may be due to the configuration of my computer, and they have been resolved.
However, I have another problem, I try to run the model with my dataset. When the edge feature of the dataset is one-dimensional, the model does not go wrong. But when the edge feature of the data set is multi-dimensional, the system reports an error. What is the reason? I found in your article that you also used some data with multi-dimensional edge features and achieved good accuracy. For my situation, how can I solve it?
I have changed edge_attr = None in the model forward function to edge_attr = data.edge_attr
The model error results are as follows:

Traceback (most recent call last):
  File "C:\Users\asus\Desktop\python\pythonProject\main.py", line 133, in <module>
    best_model = train()
  File "C:\Users\asus\Desktop\python\pythonProject\main.py", line 77, in train
    out = model(data)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\asus\Desktop\python\pythonProject\models.py", line 38, in forward
    x = F.relu(self.conv1(x, edge_index, edge_attr))
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 199, in forward
    size=None)
  File "D:\Anaconda3\lib\site-packages\torch_geometric\nn\conv\message_passing.py", line 437, in propagate
    out = self.message(**msg_kwargs)
  File "D:\Anaconda3\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 207, in message
    return x_j if edge_weight is None else edge_weight.view(-1, 1) * x_j
RuntimeError: The size of tensor a (814096) must match the size of tensor b (203524) at non-singleton dimension 0

It is obvious that the dimensions do not match, where a is 4 times that of b, and my side multi-dimensional features are also 4-dimensional. How can I solve this situation? Thanks again for your answer and look forward to your reply.

**Comment by cszhangzhen** [comment]
Hi,

We do not use any edge feature in our paper. 

Using edge features may result in errors. This is predictable. The model could learn a new edge in the pooled graph that does not exist in the original graph. You need to use additional codes to handle this situation.

**Comment by lig97** [comment]
thank you for your reply!
You said that no edge features are used, does that mean that one-dimensional edge features are not used? Even if I change edge_attr = None to edge_attr = edge_attr = data.edge_attr, the model will not use the edge features in my dataset?
Looking forward to your reply, thank you.

**Comment by cszhangzhen** [comment]
Hi,

I mean we do not use the edge features in the original dataset (if they have edge features).

Actually, we learn the edge weights to re-connect nodes in the pooled graph. Thus, the edge_attr in the codes actually means edge_weight. This is the reason why it only works for one-dimensional edge features.

If you want it to support multi-dimensional edge features, you need to revise the code on the structure learning part. One natural question is how to initialize new edge's edge features. When calculating edge weights, you also need to take edge features into consideration in the attention mechanism.

**Comment by lig97** [comment]
ok, i see, thanks for your reply!
